import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import './StartGame.css';

interface Player {
  id: string;
  name: string;
}

const WS_URL = import.meta.env.VITE_WS_URL || 'ws://localhost:3002';

function StartGame() {
  const navigate = useNavigate();
  const [gameCode, setGameCode] = useState<string | null>(null);
  const [teamA, setTeamA] = useState<Player[]>([]);
  const [teamB, setTeamB] = useState<Player[]>([]);
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [quizTopic, setQuizTopic] = useState<string>('');
  const [isGeneratingQuiz, setIsGeneratingQuiz] = useState(false);
  const wsRef = useRef<WebSocket | null>(null);

  const handleStartGame = () => {
    // Validate topic
    if (!quizTopic.trim()) {
      setError('Please enter a quiz topic');
      return;
    }

    // Close existing connection if any
    if (wsRef.current) {
      wsRef.current.close();
      wsRef.current = null;
    }

    setError(null);
    setIsConnecting(true);
    setIsGeneratingQuiz(true);

    try {
      // Connect to WebSocket server with timeout
      const ws = new WebSocket(WS_URL);
      wsRef.current = ws;

      // Set a connection timeout
      const connectionTimeout = setTimeout(() => {
        if (ws.readyState === WebSocket.CONNECTING) {
          ws.close();
          setError('Connection timeout. Make sure the WebSocket server is running on port 3002.');
          setIsConnecting(false);
          setIsGeneratingQuiz(false);
        }
      }, 60000); // 60 second timeout (quiz generation can take time)

      ws.onopen = () => {
        console.log('WebSocket connected');
        clearTimeout(connectionTimeout);
        setIsConnecting(false);
        // Request to create a new game with topic
        try {
          ws.send(JSON.stringify({
            type: 'create_game',
            topic: quizTopic.trim()
          }));
        } catch (error) {
          console.error('Error sending message:', error);
          setError('Failed to send message to server');
          setIsConnecting(false);
          setIsGeneratingQuiz(false);
        }
      };

      ws.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          console.log('Received message:', data);

          switch (data.type) {
            case 'quiz_generating':
              // Quiz is being generated by AI
              console.log('Quiz is being generated...');
              setIsGeneratingQuiz(true);
              break;

            case 'game_created':
              setGameCode(data.gameCode);
              setTeamA([]);
              setTeamB([]);
              setError(null);
              setIsGeneratingQuiz(false);
              break;

            case 'game_state':
              setTeamA(data.teamA || []);
              setTeamB(data.teamB || []);
              break;

            case 'error':
              console.error('WebSocket error:', data.message);
              setError(data.message);
              setIsConnecting(false);
              setIsGeneratingQuiz(false);
              break;
          }
        } catch (error) {
          console.error('Error parsing WebSocket message:', error);
          setError('Error processing server response');
          setIsConnecting(false);
        }
      };

      ws.onerror = (error) => {
        console.error('WebSocket error:', error);
        clearTimeout(connectionTimeout);
        setError('Failed to connect to server. Make sure the WebSocket server is running on port 3002.');
        setIsConnecting(false);
      };

      ws.onclose = (event) => {
        console.log('WebSocket disconnected', event.code, event.reason);
        clearTimeout(connectionTimeout);
        setIsConnecting(false);
        // Only show error if it was an unexpected close (not a clean close)
        if (event.code !== 1000 && !gameCode && event.code !== 1006) {
          // 1006 is abnormal closure, which happens when server isn't running
          if (event.code === 1006) {
            setError('Cannot connect to server. Please start the WebSocket server with: npm run dev:server');
          } else {
            setError('Connection closed. Please try again.');
          }
        }
      };
    } catch (error) {
      console.error('Error creating WebSocket:', error);
      setError('Failed to create connection. Please check your browser console.');
      setIsConnecting(false);
    }
  };

  // Cleanup WebSocket on unmount
  useEffect(() => {
    return () => {
      if (wsRef.current) {
        wsRef.current.close();
      }
    };
  }, []);

  const canStartGame = teamA.length === 1 && teamB.length === 1;

  const handleBeginGame = () => {
    if (canStartGame && gameCode) {
      // Send start game message to server
      if (wsRef.current && wsRef.current.readyState === WebSocket.OPEN) {
        wsRef.current.send(JSON.stringify({
          type: 'start_game',
          gameCode
        }));
      }
      // Navigate to quiz game screen
      navigate('/quiz/game', { state: { gameCode } });
    }
  };

  return (
    <div className="start-game-container">
      <div className="start-game-card">
        {!gameCode ? (
          <>
            <h1 className="start-game-title">Quiz Game</h1>
            <p className="start-game-subtitle">Create a new AI-powered quiz game</p>

            {error && (
              <div className="error-message" style={{
                marginBottom: '1rem',
                padding: '0.75rem 1rem',
                background: 'rgba(255, 68, 68, 0.2)',
                border: '2px solid rgba(255, 68, 68, 0.5)',
                borderRadius: '12px',
                color: '#ff6b6b',
                fontSize: '0.95rem',
                fontWeight: 600
              }}>
                {error}
              </div>
            )}

            {/* Topic Input */}
            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{
                display: 'block',
                fontSize: '1.1rem',
                fontWeight: 700,
                color: '#ffd700',
                marginBottom: '0.75rem',
                textTransform: 'uppercase',
                letterSpacing: '0.05em'
              }}>
                🎯 Quiz Topic
              </label>
              <input
                type="text"
                value={quizTopic}
                onChange={(e) => setQuizTopic(e.target.value)}
                placeholder="Enter a topic (e.g., World War 2, Solar System, JavaScript)"
                disabled={isConnecting || isGeneratingQuiz}
                style={{
                  width: '100%',
                  padding: '1rem 1.25rem',
                  fontSize: '1.05rem',
                  borderRadius: '12px',
                  border: '2px solid rgba(255, 215, 0, 0.3)',
                  background: 'rgba(255, 255, 255, 0.05)',
                  color: 'white',
                  fontWeight: 600,
                  transition: 'all 0.3s ease',
                  opacity: (isConnecting || isGeneratingQuiz) ? 0.5 : 1
                }}
                onFocus={(e) => {
                  e.target.style.borderColor = '#ffd700';
                  e.target.style.boxShadow = '0 0 0 3px rgba(255, 215, 0, 0.2)';
                  e.target.style.background = 'rgba(255, 255, 255, 0.08)';
                }}
                onBlur={(e) => {
                  e.target.style.borderColor = 'rgba(255, 215, 0, 0.3)';
                  e.target.style.boxShadow = 'none';
                  e.target.style.background = 'rgba(255, 255, 255, 0.05)';
                }}
              />
              <p style={{
                marginTop: '0.5rem',
                fontSize: '0.9rem',
                color: 'rgba(255, 255, 255, 0.6)',
                fontStyle: 'italic'
              }}>
                AI will generate 15 questions about this topic
              </p>
            </div>

            <button
              className="start-game-button"
              onClick={handleStartGame}
              disabled={isConnecting || isGeneratingQuiz || !quizTopic.trim()}
            >
              {isGeneratingQuiz ? '🤖 Generating Quiz...' : isConnecting ? 'Connecting...' : '🚀 Create Game'}
            </button>

            {isGeneratingQuiz && (
              <p style={{
                marginTop: '1rem',
                fontSize: '0.95rem',
                color: '#ffd700',
                fontWeight: 600,
                animation: 'pulse 1.5s ease-in-out infinite'
              }}>
                ⚡ AI is crafting your quiz questions...
              </p>
            )}

            <a href="/quiz/join" className="join-link">
              Or join an existing game
            </a>
          </>
        ) : (
          <div className="game-lobby">
            <div className="game-header">
              <h1 className="start-game-title">Game Lobby</h1>
              <p className="start-game-subtitle">Share this code with players to join</p>
              <div className="game-code-container">
                <div className="game-code">{gameCode}</div>
              </div>
            </div>

            <div className="teams-container">
              <div className="team-section team-a">
                <h2 className="team-title">Team A</h2>
                <div className="player-list">
                  {teamA.length === 0 ? (
                    <div className="empty-team">Waiting for players...</div>
                  ) : (
                    teamA.map((player) => (
                      <div key={player.id} className="player-item">
                        <span className="player-name">{player.name}</span>
                      </div>
                    ))
                  )}
                </div>
                <div className="team-count">{teamA.length} player{teamA.length !== 1 ? 's' : ''}</div>
              </div>

              <div className="team-divider"></div>

              <div className="team-section team-b">
                <h2 className="team-title">Team B</h2>
                <div className="player-list">
                  {teamB.length === 0 ? (
                    <div className="empty-team">Waiting for players...</div>
                  ) : (
                    teamB.map((player) => (
                      <div key={player.id} className="player-item">
                        <span className="player-name">{player.name}</span>
                      </div>
                    ))
                  )}
                </div>
                <div className="team-count">{teamB.length} player{teamB.length !== 1 ? 's' : ''}</div>
              </div>
            </div>

            <div className="game-actions">
              <button
                className={`start-game-button begin-game ${canStartGame ? 'active' : 'disabled'}`}
                onClick={handleBeginGame}
                disabled={!canStartGame}
              >
                Start Game
              </button>
              {!canStartGame && (
                <p className="start-game-hint">
                  Waiting for 2 players (1 in each team)...
                </p>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default StartGame;
